import { useEffect, useMemo, useState } from "react";
import { api, formatApiError } from "@/lib/api";
import { Download, FileSpreadsheet, IndianRupee, PackageCheck, RefreshCw, ShoppingBag, Users } from "lucide-react";
import { exportRowsToExcel, exportRowsToPdf } from "@/utils/exportData";

const money = (v) => new Intl.NumberFormat("en-IN", {style:"currency",currency:"INR",maximumFractionDigits:0}).format(v||0);
const orderColumns=[{label:"Order",value:x=>x.order_number||x.order_id},{label:"Status",value:x=>x.status},{label:"Total",value:x=>x.total},{label:"Customer",value:x=>x.customer_name||x.user_name||"Customer"},{label:"Date",value:x=>x.created_at?new Date(x.created_at).toLocaleDateString("en-IN"):""}];
export default function AdminReports(){
 const [data,setData]=useState(null),[loading,setLoading]=useState(true),[error,setError]=useState("");
 const load=async()=>{setLoading(true);try{const r=await api.get("/admin/reports");setData(r.data);setError("");}catch(e){setError(formatApiError(e));}finally{setLoading(false);}};useEffect(()=>{load();},[]);
 const summaryRows=useMemo(()=>data?[{metric:"Products",value:data.products},{metric:"Categories",value:data.categories},{metric:"Customers",value:data.customers},{metric:"Managers",value:data.managers},{metric:"Orders",value:data.orders},{metric:"Pending orders",value:data.pending_orders},{metric:"Delivered orders",value:data.delivered_orders},{metric:"Revenue",value:data.revenue}]:[],[data]);
 const summaryCols=[{label:"Metric",value:x=>x.metric},{label:"Value",value:x=>x.value}];
 return <div className="admin-page"><div className="page-heading-row"><div><span className="eyebrow">Business intelligence</span><h1>Reports & Exports</h1><p>Download clean PDF and Excel reports anytime.</p></div><button className="btn btn-secondary" onClick={load}><RefreshCw size={18}/> Refresh</button></div>{error&&<div className="alert alert-error">{error}</div>}
 <section className="metric-grid compact"><div className="metric-card static"><span className="metric-icon"><IndianRupee/></span><span className="metric-copy"><small>Total revenue</small><strong>{money(data?.revenue)}</strong></span></div><div className="metric-card static"><span className="metric-icon"><ShoppingBag/></span><span className="metric-copy"><small>Total orders</small><strong>{data?.orders||0}</strong></span></div><div className="metric-card static"><span className="metric-icon"><PackageCheck/></span><span className="metric-copy"><small>Delivered</small><strong>{data?.delivered_orders||0}</strong></span></div><div className="metric-card static"><span className="metric-icon"><Users/></span><span className="metric-copy"><small>Customers</small><strong>{data?.customers||0}</strong></span></div></section>
 <section className="report-card-grid"><div className="panel export-card"><div><h2>Business summary</h2><p>Key totals for products, orders, users and revenue.</p></div><div className="export-actions"><button className="btn btn-ghost" disabled={loading} onClick={()=>exportRowsToPdf({rows:summaryRows,columns:summaryCols,fileName:"zanszii-business-summary",title:"Zanszii Business Summary"})}><Download size={18}/> Export PDF</button><button className="btn btn-primary" disabled={loading} onClick={()=>exportRowsToExcel({rows:summaryRows,columns:summaryCols,fileName:"zanszii-business-summary",sheetName:"Summary"})}><FileSpreadsheet size={18}/> Export Excel</button></div></div><div className="panel export-card"><div><h2>Recent orders</h2><p>Latest orders with status, customer and value.</p></div><div className="export-actions"><button className="btn btn-ghost" disabled={loading} onClick={()=>exportRowsToPdf({rows:data?.recent_orders||[],columns:orderColumns,fileName:"zanszii-recent-orders",title:"Zanszii Recent Orders",landscape:true})}><Download size={18}/> Export PDF</button><button className="btn btn-primary" disabled={loading} onClick={()=>exportRowsToExcel({rows:data?.recent_orders||[],columns:orderColumns,fileName:"zanszii-recent-orders",sheetName:"Orders"})}><FileSpreadsheet size={18}/> Export Excel</button></div></div></section>
 </div>;
}

