import { useEffect, useMemo, useState } from "react";
import { api, formatApiError } from "@/lib/api";
import { Download, FileSpreadsheet, PackagePlus, Pencil, RefreshCw, Search, Trash2, X } from "lucide-react";
import { exportRowsToExcel, exportRowsToPdf } from "@/utils/exportData";

const blank = { name:"", description:"", category_id:"", price:"", stock:"", unit:"piece", image_url:"", active:true, featured:false };
const money = (v) => new Intl.NumberFormat("en-IN", { style:"currency", currency:"INR" }).format(v || 0);
const columns = [
  { label:"Product", value:x=>x.name }, { label:"Category", value:x=>x.category?.name || "" }, { label:"Price", value:x=>x.price }, { label:"Stock", value:x=>x.stock }, { label:"Unit", value:x=>x.unit }, { label:"Status", value:x=>x.active ? "Active" : "Inactive" },
];

export default function AdminProducts(){
 const [items,setItems]=useState([]), [categories,setCategories]=useState([]), [query,setQuery]=useState(""), [category,setCategory]=useState("all");
 const [modal,setModal]=useState(false), [editing,setEditing]=useState(null), [form,setForm]=useState(blank), [loading,setLoading]=useState(true), [saving,setSaving]=useState(false), [error,setError]=useState("");
 const load=async()=>{setLoading(true);setError("");try{const [p,c]=await Promise.all([api.get("/products?include_inactive=true"),api.get("/categories?include_inactive=true")]);setItems(p.data);setCategories(c.data);}catch(e){setError(formatApiError(e));}finally{setLoading(false);}};
 useEffect(()=>{load();},[]);
 const filtered=useMemo(()=>items.filter(x=>(category==="all"||x.category_id===category)&&`${x.name} ${x.description||""} ${x.category?.name||""}`.toLowerCase().includes(query.toLowerCase())),[items,category,query]);
 const openCreate=()=>{setEditing(null);setForm({...blank,category_id:categories[0]?.category_id||""});setModal(true);};
 const openEdit=(x)=>{setEditing(x);setForm({name:x.name,description:x.description||"",category_id:x.category_id,price:x.price,stock:x.stock,unit:x.unit||"piece",image_url:x.image_url||"",active:x.active!==false,featured:!!x.featured});setModal(true);};
 const save=async(e)=>{e.preventDefault();setSaving(true);setError("");const payload={...form,price:Number(form.price),stock:Number(form.stock),images:[]};try{editing?await api.patch(`/products/${editing.product_id}`,payload):await api.post("/products",payload);setModal(false);await load();}catch(err){setError(formatApiError(err));}finally{setSaving(false);}};
 const remove=async(x)=>{if(!window.confirm(`Delete “${x.name}”?`))return;try{await api.delete(`/products/${x.product_id}`);await load();}catch(e){setError(formatApiError(e));}};
 return <div className="admin-page"><div className="page-heading-row"><div><span className="eyebrow">Inventory control</span><h1>Products</h1><p>Add products, manage stock and keep pricing clear.</p></div><button className="btn btn-primary" onClick={openCreate} disabled={!categories.length}><PackagePlus size={18}/> Add product</button></div>
 {error&&<div className="alert alert-error">{error}</div>}{!categories.length&&!loading&&<div className="alert alert-info">Create a category before adding your first product.</div>}
 <div className="panel toolbar-panel"><div className="filter-group"><div className="search-field"><Search size={18}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search products…"/></div><select value={category} onChange={e=>setCategory(e.target.value)}><option value="all">All categories</option>{categories.map(c=><option key={c.category_id} value={c.category_id}>{c.name}</option>)}</select></div><div className="toolbar-actions"><button className="btn btn-ghost" onClick={()=>exportRowsToPdf({rows:filtered,columns,fileName:"zanszii-products",title:"Zanszii Product Report",landscape:true})}><Download size={17}/> PDF</button><button className="btn btn-ghost" onClick={()=>exportRowsToExcel({rows:filtered,columns,fileName:"zanszii-products",sheetName:"Products"})}><FileSpreadsheet size={17}/> Excel</button><button className="icon-btn bordered" onClick={load}><RefreshCw size={18}/></button></div></div>
 <div className="panel"><div className="table-wrap"><table className="data-table"><thead><tr><th>Product</th><th>Category</th><th>Price</th><th>Stock</th><th>Status</th><th className="actions-col">Actions</th></tr></thead><tbody>{loading?<tr><td colSpan="6" className="empty-cell">Loading products…</td></tr>:filtered.length?filtered.map(x=><tr key={x.product_id}><td><div className="product-cell"><div className="product-thumb">{x.image_url?<img src={x.image_url} alt=""/>:<span>{x.name?.[0]}</span>}</div><div><strong>{x.name}</strong><small>{x.unit||"piece"}{x.featured?" · Featured":""}</small></div></div></td><td>{x.category?.name||"—"}</td><td><strong>{money(x.price)}</strong></td><td><span className={`stock-pill ${x.stock<=5?"low":""}`}>{x.stock}</span></td><td><span className={`status-chip ${x.active?"status-active":"status-inactive"}`}>{x.active?"Active":"Inactive"}</span></td><td><div className="row-actions"><button onClick={()=>openEdit(x)}><Pencil size={17}/></button><button className="danger" onClick={()=>remove(x)}><Trash2 size={17}/></button></div></td></tr>):<tr><td colSpan="6" className="empty-cell">No products found.</td></tr>}</tbody></table></div></div>
 {modal&&<div className="modal-backdrop"><div className="modal-card modal-wide"><div className="modal-header"><div><h2>{editing?"Edit product":"New product"}</h2><p>Fill the essential product details.</p></div><button className="icon-btn" onClick={()=>setModal(false)}><X/></button></div><form onSubmit={save} className="modal-form form-grid"><label className="span-2">Product name<input required value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/></label><label>Category<select required value={form.category_id} onChange={e=>setForm({...form,category_id:e.target.value})}><option value="">Select category</option>{categories.map(c=><option key={c.category_id} value={c.category_id}>{c.name}</option>)}</select></label><label>Unit<input required value={form.unit} onChange={e=>setForm({...form,unit:e.target.value})}/></label><label>Price (₹)<input type="number" min="0.01" step="0.01" required value={form.price} onChange={e=>setForm({...form,price:e.target.value})}/></label><label>Stock quantity<input type="number" min="0" required value={form.stock} onChange={e=>setForm({...form,stock:e.target.value})}/></label><label className="span-2">Image URL<input value={form.image_url} onChange={e=>setForm({...form,image_url:e.target.value})} placeholder="https://…"/></label><label className="span-2">Description<textarea rows="4" value={form.description} onChange={e=>setForm({...form,description:e.target.value})}/></label><label className="switch-row"><input type="checkbox" checked={form.active} onChange={e=>setForm({...form,active:e.target.checked})}/><span>Active</span></label><label className="switch-row"><input type="checkbox" checked={form.featured} onChange={e=>setForm({...form,featured:e.target.checked})}/><span>Featured product</span></label><div className="modal-actions span-2"><button type="button" className="btn btn-ghost" onClick={()=>setModal(false)}>Cancel</button><button className="btn btn-primary" disabled={saving}>{saving?"Saving…":"Save product"}</button></div></form></div></div>}
 </div>;
}

