import { useEffect, useMemo, useState } from "react";
import { api, formatApiError } from "../../lib/api";

const emptyForm = { name:"", email:"", phone:"", password:"", active:true };
const label = (value) => String(value || "").replaceAll("_"," ").replace(/\b\w/g,c=>c.toUpperCase());

export default function AdminManagers(){
  const [managers,setManagers]=useState([]),[orders,setOrders]=useState([]),[form,setForm]=useState(emptyForm),[editing,setEditing]=useState(null),[showForm,setShowForm]=useState(false),[search,setSearch]=useState(""),[error,setError]=useState(""),[saving,setSaving]=useState(false);

  const load=async()=>{try{setError("");const [m,o]=await Promise.all([api.get("/admin/managers"),api.get("/admin/orders")]);setManagers(m.data||[]);setOrders(o.data||[])}catch(e){setError(formatApiError(e?.response?.data?.detail)||"Unable to load managers.")}};
  useEffect(()=>{load()},[]);

  const rows=useMemo(()=>managers.map(manager=>{const managerId=manager.user_id||manager.manager_id||manager.id;return {...manager,managerId,activeOrders:orders.filter(o=>o.manager_id===managerId&&!['delivered','cancelled'].includes(o.status)).length,deliveredOrders:orders.filter(o=>o.manager_id===managerId&&o.status==='delivered').length}}),[managers,orders]);
  const shown=useMemo(()=>{const t=search.trim().toLowerCase();return !t?rows:rows.filter(m=>[m.name,m.email,m.phone].filter(Boolean).some(v=>String(v).toLowerCase().includes(t)))},[rows,search]);

  const openCreate=()=>{setEditing(null);setForm(emptyForm);setShowForm(true)};
  const openEdit=(m)=>{setEditing(m);setForm({name:m.name||"",email:m.email||"",phone:m.phone||"",password:"",active:m.active!==false});setShowForm(true)};

  const save=async(e)=>{e.preventDefault();try{setSaving(true);setError("");const payload={name:form.name.trim(),email:form.email.trim(),phone:form.phone.trim(),active:form.active};if(form.password)payload.password=form.password;if(editing)await api.patch(`/admin/managers/${editing.managerId}`,payload);else await api.post("/admin/managers",payload);setShowForm(false);setEditing(null);setForm(emptyForm);await load()}catch(err){setError(formatApiError(err?.response?.data?.detail)||"Unable to save manager.")}finally{setSaving(false)}};
  const toggle=async(m)=>{try{await api.patch(`/admin/managers/${m.managerId}/status`,{active:m.active===false});await load()}catch(err){setError(formatApiError(err?.response?.data?.detail)||"Unable to update manager.")}};
  const remove=async(m)=>{if(!window.confirm(`Delete ${m.name}?`))return;try{await api.delete(`/admin/managers/${m.managerId}`);await load()}catch(err){setError(formatApiError(err?.response?.data?.detail)||"Unable to delete manager.")}};
  const assign=async(orderId,managerId)=>{try{await api.patch(`/admin/orders/${orderId}/assign`,{manager_id:managerId||null});await load()}catch(err){setError(formatApiError(err?.response?.data?.detail)||"Unable to assign manager.")}};
  const assignable=orders.filter(o=>!["delivered","cancelled"].includes(o.status));

  return <div className="space-y-6">
    <div className="flex flex-col gap-4 lg:flex-row lg:items-end lg:justify-between"><div><p className="text-sm font-bold text-[#0F4C9C]">Admin</p><h1 className="text-3xl font-black">Manager Management</h1><p className="text-slate-500">Add managers and assign customer orders.</p></div><button onClick={openCreate} className="rounded-xl bg-[#0F4C9C] px-5 py-3 font-bold text-white">+ Add Manager</button></div>
    {error&&<div className="rounded-2xl bg-red-50 p-4 text-red-700">{error}</div>}
    <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{[["Total Managers",rows.length],["Active Managers",rows.filter(m=>m.active!==false).length],["Active Deliveries",rows.reduce((s,m)=>s+m.activeOrders,0)],["Completed Deliveries",rows.reduce((s,m)=>s+m.deliveredOrders,0)]].map(([t,v])=><div key={t} className="rounded-3xl border bg-white p-5 shadow-sm"><p className="text-sm font-semibold text-slate-500">{t}</p><p className="mt-2 text-3xl font-black">{v}</p></div>)}</div>
    <div className="rounded-3xl border bg-white p-4"><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search manager..." className="w-full rounded-2xl border px-4 py-3"/></div>
    <div className="overflow-x-auto rounded-3xl border bg-white"><table className="min-w-full text-sm"><thead className="bg-[#F5F9FF]"><tr>{["Manager","Contact","Active Orders","Delivered","Status","Actions"].map(h=><th key={h} className="px-4 py-3 text-left">{h}</th>)}</tr></thead><tbody>{shown.map(m=><tr key={m.managerId||m.email} className="border-t"><td className="px-4 py-4 font-black">{m.name}</td><td className="px-4 py-4">{m.phone||"-"}<div className="text-xs text-slate-500">{m.email||"-"}</div></td><td className="px-4 py-4 font-black">{m.activeOrders}</td><td className="px-4 py-4 font-black">{m.deliveredOrders}</td><td className="px-4 py-4"><span className={`rounded-full px-3 py-1 text-xs font-bold ${m.active===false?'bg-red-50 text-red-700':'bg-emerald-50 text-emerald-700'}`}>{m.active===false?'Inactive':'Active'}</span></td><td className="px-4 py-4"><div className="flex gap-3"><button onClick={()=>openEdit(m)} className="font-bold text-[#0F4C9C]">Edit</button><button onClick={()=>toggle(m)} className="font-bold text-amber-600">{m.active===false?'Activate':'Deactivate'}</button><button onClick={()=>remove(m)} className="font-bold text-red-600">Delete</button></div></td></tr>)}{shown.length===0&&<tr><td colSpan="6" className="px-4 py-12 text-center">No managers found.</td></tr>}</tbody></table></div>

    <div className="rounded-3xl border bg-white p-5"><p className="text-sm font-bold text-[#0F4C9C]">Assignment Desk</p><h2 className="text-2xl font-black">Assign Orders to Managers</h2><div className="mt-5 overflow-x-auto rounded-2xl border"><table className="min-w-full text-sm"><thead className="bg-[#F5F9FF]"><tr>{["Order","Customer","Status","Current Manager","Assign"].map(h=><th key={h} className="px-4 py-3 text-left">{h}</th>)}</tr></thead><tbody>{assignable.map(o=><tr key={o.order_id} className="border-t"><td className="px-4 py-4 font-black">{o.order_number||o.order_id}</td><td className="px-4 py-4">{o.customer_name||"Customer"}<div className="text-xs text-slate-500">{o.phone||o.customer_phone||"-"}</div></td><td className="px-4 py-4">{label(o.status)}</td><td className="px-4 py-4">{o.manager_name||"Unassigned"}</td><td className="px-4 py-4"><select value={o.manager_id||""} onChange={e=>assign(o.order_id,e.target.value)} className="min-w-[180px] rounded-xl border px-3 py-2"><option value="">Unassigned</option>{rows.filter(m=>m.active!==false).map(m=><option key={m.managerId} value={m.managerId}>{m.name} ({m.activeOrders} active)</option>)}</select></td></tr>)}{assignable.length===0&&<tr><td colSpan="5" className="px-4 py-10 text-center">No active orders.</td></tr>}</tbody></table></div></div>

    {showForm&&<div className="fixed inset-0 z-50 flex items-center justify-center bg-black/50 p-4"><form onSubmit={save} className="w-full max-w-xl rounded-3xl bg-white p-6"><div className="flex justify-between"><div><p className="text-sm font-bold text-[#0F4C9C]">Admin</p><h2 className="text-2xl font-black">{editing?'Edit Manager':'Add Manager'}</h2></div><button type="button" onClick={()=>setShowForm(false)} className="rounded-xl border px-4 py-2 font-bold">Close</button></div><div className="mt-6 grid gap-4"><input required value={form.name} onChange={e=>setForm({...form,name:e.target.value})} placeholder="Manager name" className="rounded-2xl border px-4 py-3"/><input required type="email" value={form.email} onChange={e=>setForm({...form,email:e.target.value})} placeholder="Email" className="rounded-2xl border px-4 py-3"/><input required value={form.phone} onChange={e=>setForm({...form,phone:e.target.value})} placeholder="Phone" className="rounded-2xl border px-4 py-3"/><input required={!editing} type="password" value={form.password} onChange={e=>setForm({...form,password:e.target.value})} placeholder={editing?'New password (optional)':'Temporary password'} className="rounded-2xl border px-4 py-3"/><label className="flex items-center gap-3 rounded-2xl bg-slate-50 p-4"><input type="checkbox" checked={form.active} onChange={e=>setForm({...form,active:e.target.checked})}/><span className="font-bold">Manager account active</span></label><button disabled={saving} className="rounded-2xl bg-[#0F4C9C] px-5 py-3 font-black text-white">{saving?'Saving...':editing?'Update Manager':'Create Manager'}</button></div></form></div>}
  </div>;
}
